### ISSUE TITLE
Admin cant delete a project

### ISSUE THREAD

**Issue by saooms** [hmooms/Emphasis#12]
### Explanation
When an admin tries to delete a project an error shows up and the project isn't deleted

### How to reproduce

1. Go to: Go To: [https:..emphasis](https://emphasis-projects.herokuapp.com/login)
2. Login with:

- admin@account.nl
- password

3. Click on a project
4. Click on "VERWIJDEREN"
5. Enter password
6. Click on "PROJECT VERWIJDEREN"
![image](https://user-images.githubusercontent.com/31506257/175097697-e332c44a-96f2-4cec-b7c7-47554379ca88.png)

Found by Stijn Ooms
pre release 0.2.0
22-06-2022

**Comment by hmooms** [comment]
The migration wasn't run yet, works as intended after migration
